version: "3.7"

services:
  postgres:
    container_name: postgress_isolations
    image: postgres:13.3
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  mysql:
    image: mysql:latest
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - ./volumes/mysql.cnf:/etc/mysql/conf.d/mysql.cnf






